/*
========================================================
TOP SELLING PRODUCT IN EACH CATEGORY
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Identify the highest revenue-generating product within
each product category.

Formula:
Revenue =
SUM(Quantity × Unit Price)

Technique Used:
1. Aggregate revenue for each product.
2. Use ROW_NUMBER() to rank products within each category.
3. PARTITION BY Category.
4. ORDER BY Revenue DESC.
5. Filter Rank = 1.

Business Use:
This analysis helps RetailIQ identify the best-selling
product in every category. The results support
inventory planning, product promotion, pricing
strategies, and category performance analysis.

Window Function Used:
ROW_NUMBER()

Reason:
Returns exactly ONE highest revenue product
from each category.

========================================================
*/

WITH top_products AS
(
    SELECT
        c.category_id,
        c.category_name,
        p.product_id,
        p.model,
        SUM(oi.quantity * oi.unit_price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY c.category_id
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS row_num

    FROM category c

    JOIN product p
        ON c.category_id = p.category_id

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        c.category_id,
        c.category_name,
        p.product_id,
        p.model
)

SELECT
    category_name,
    model,
    total_revenue
FROM top_products
WHERE row_num = 1
ORDER BY category_name;

/*
========================================================
TOP CUSTOMER BY REVENUE IN EACH STORE
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Identify the customer who generated the highest revenue
within each store.

Formula:
Revenue =
SUM(Quantity × Unit Price)

Technique Used:
1. Aggregate customer revenue for each store.
2. Use ROW_NUMBER() to rank customers within each store.
3. PARTITION BY Store.
4. ORDER BY Revenue DESC.
5. Filter Row Number = 1.

Business Use:
This analysis helps RetailIQ identify the highest-value
customer for every store. The results support customer
relationship management, loyalty programs, and targeted
marketing strategies.

Window Function Used:
ROW_NUMBER()

Reason:
Returns exactly ONE highest revenue customer
from each store.

========================================================
*/

WITH high_customer_cte AS
(
    SELECT
        s.store_id,
        s.store_location,
        c.customer_id,
        c.name AS customer_name,

        SUM(oi.quantity * oi.unit_price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY s.store_id
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS row_num

    FROM store s

    JOIN orders o
        ON s.store_id = o.store_id

    JOIN customer c
        ON o.customer_id = c.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        s.store_id,
        s.store_location,
        c.customer_id,
        c.name
)

SELECT
    store_location,
    customer_name,
    total_revenue
FROM high_customer_cte
WHERE row_num = 1
ORDER BY store_location;

/*
========================================================
TOP EMPLOYEE BY REVENUE IN EACH STORE
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Identify the employee who generated the highest
sales revenue within each store.

Formula:
Revenue =
SUM(Quantity × Unit Price)

Technique Used:
1. Aggregate revenue generated by each employee.
2. Use ROW_NUMBER() to rank employees within each store.
3. PARTITION BY Store.
4. ORDER BY Revenue DESC.
5. Filter Row Number = 1.

Business Use:
This analysis helps RetailIQ identify the best
performing employee in every store. The results
support performance evaluation, incentive programs,
sales recognition, and workforce planning.

Window Function Used:
ROW_NUMBER()

Reason:
Returns exactly ONE highest revenue employee
from each store.

========================================================
*/

WITH high_revenue_emp AS
(
    SELECT
        s.store_id,
        s.store_location,
        e.employee_id,
        e.employee_name,

        SUM(oi.quantity * oi.unit_price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY s.store_id
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS row_num

    FROM employee e

    JOIN store s
        ON e.store_id = s.store_id

    JOIN orders o
        ON s.store_id = o.store_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        s.store_id,
        s.store_location,
        e.employee_id,
        e.employee_name
)

SELECT
    store_location,
    employee_name,
    total_revenue
FROM high_revenue_emp
WHERE row_num = 1
ORDER BY store_location;

/*
========================================================
TOP REVENUE GENERATING BRAND IN EACH CATEGORY
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Identify the brand that generated the highest sales
revenue within each product category.

Formula:
Revenue =
SUM(Quantity × Unit Price)

Technique Used:
1. Aggregate revenue for each brand within every category.
2. Use ROW_NUMBER() to rank brands by revenue.
3. PARTITION BY Category.
4. ORDER BY Revenue DESC.
5. Filter Row Number = 1.

Business Use:
This analysis helps RetailIQ identify the strongest
performing brand in every category. The results support
supplier negotiations, promotional planning, category
management, and strategic business decisions.

Window Function Used:
ROW_NUMBER()

Reason:
Returns exactly ONE highest revenue generating brand
from each category.

========================================================
*/

WITH high_revenue_brand AS
(
    SELECT
        c.category_id,
        c.category_name,
        p.brand,

        SUM(oi.quantity * oi.unit_price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY c.category_id
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS row_num

    FROM category c

    JOIN product p
        ON c.category_id = p.category_id

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        c.category_id,
        c.category_name,
        p.brand
)

SELECT
    category_name,
    brand,
    total_revenue
FROM high_revenue_brand
WHERE row_num = 1
ORDER BY category_name;

/*
========================================================
LOWEST SELLING PRODUCT IN EACH CATEGORY
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Identify the product that generated the lowest sales
revenue within each product category.

Formula:
Revenue =
SUM(Quantity × Unit Price)

Technique Used:
1. Aggregate revenue for each product.
2. Use ROW_NUMBER() to rank products within each category.
3. PARTITION BY Category.
4. ORDER BY Revenue ASC.
5. Filter Row Number = 1.

Business Use:
This analysis helps RetailIQ identify the weakest
performing product in every category. The results
support inventory optimization, product lifecycle
management, pricing decisions, and product
discontinuation analysis.

Window Function Used:
ROW_NUMBER()

Reason:
Returns exactly ONE lowest revenue generating product
from each category.

========================================================
*/

WITH low_revenue AS
(
    SELECT
        c.category_id,
        c.category_name,
        p.product_id,
        p.model,

        SUM(oi.quantity * oi.unit_price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY c.category_id
            ORDER BY SUM(oi.quantity * oi.unit_price) ASC
        ) AS row_num

    FROM category c

    JOIN product p
        ON c.category_id = p.category_id

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        c.category_id,
        c.category_name,
        p.product_id,
        p.model
)

SELECT
    category_name,
    model,
    total_revenue
FROM low_revenue
WHERE row_num = 1
ORDER BY category_name;

/*
========================================================
TOP SELLING PRODUCT WITHIN EACH BRAND
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Identify the highest revenue-generating product
within each brand.

Formula:
Revenue =
SUM(Quantity × Unit Price)

Technique Used:
1. Aggregate revenue for each product within every brand.
2. Use ROW_NUMBER() to rank products by revenue.
3. PARTITION BY Brand.
4. ORDER BY Revenue DESC.
5. Filter Row Number = 1.

Business Use:
This analysis helps RetailIQ identify the flagship
product of every brand. The results support product
positioning, promotional planning, inventory decisions,
and brand performance analysis.

Window Function Used:
ROW_NUMBER()

Reason:
Returns exactly ONE highest revenue-generating product
within each brand.

========================================================
*/

WITH top_selling_product AS
(
    SELECT
        p.brand,
        p.product_id,
        p.model,

        SUM(oi.quantity * oi.unit_price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY p.brand
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS row_num

    FROM product p

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        p.brand,
        p.product_id,
        p.model
)

SELECT
    brand,
    model,
    total_revenue
FROM top_selling_product
WHERE row_num = 1
ORDER BY brand;

/*
========================================================
TOP CUSTOMER BY REVENUE WITHIN EACH PAYMENT METHOD
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Identify the customer who generated the highest sales
revenue for each payment method.

Formula:
Revenue =
SUM(Quantity × Unit Price)

Technique Used:
1. Aggregate customer revenue for each payment method.
2. Use ROW_NUMBER() to rank customers by revenue.
3. PARTITION BY Payment Method.
4. ORDER BY Revenue DESC.
5. Filter Row Number = 1.

Business Use:
This analysis helps RetailIQ identify the highest-value
customer for each payment method. The results support
customer segmentation, payment behavior analysis,
marketing campaigns, and loyalty strategies.

Window Function Used:
ROW_NUMBER()

Reason:
Returns exactly ONE highest revenue-generating customer
for each payment method.

========================================================
*/

WITH high_spender AS
(
    SELECT
        c.customer_id,
        c.name AS customer_name,
        p.payment_type,

        SUM(oi.quantity * oi.unit_price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY p.payment_type
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS row_num

    FROM customer c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN payments p
        ON o.order_id = p.order_id

    GROUP BY
        c.customer_id,
        c.name,
        p.payment_type
)

SELECT
    customer_name,
    payment_type,
    total_revenue
FROM high_spender
WHERE row_num = 1
ORDER BY payment_type;


/*
========================================================
TOP 3 REVENUE GENERATING PRODUCTS IN EACH CATEGORY
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Identify the top three revenue-generating products
within each product category.

Formula:
Revenue =
SUM(Quantity × Unit Price)

Technique Used:
1. Aggregate revenue for each product.
2. Use ROW_NUMBER() to rank products within each category.
3. PARTITION BY Category.
4. ORDER BY Revenue DESC.
5. Filter Row Number <= 3.

Business Use:
This analysis helps RetailIQ identify the top-performing
products within every category. The results support
inventory planning, promotional campaigns, product
placement, and category performance analysis.

Window Function Used:
ROW_NUMBER()

Reason:
Returns the Top 3 highest revenue-generating products
within each category.

========================================================
*/

WITH top_revenue_products AS
(
    SELECT
        c.category_id,
        c.category_name,
        p.product_id,
        p.model,

        SUM(oi.quantity * oi.unit_price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY c.category_id
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS row_num

    FROM category c

    JOIN product p
        ON c.category_id = p.category_id

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        c.category_id,
        c.category_name,
        p.product_id,
        p.model
)

SELECT
    category_name,
    model,
    total_revenue

FROM top_revenue_products

WHERE row_num <= 3

ORDER BY
    category_name,
    row_num;

/*
========================================================
RUNNING MONTHLY REVENUE
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Calculate the cumulative (running) sales revenue
month by month throughout the year.

Formula:
Monthly Revenue =
SUM(Quantity × Unit Price)

Running Revenue =
SUM(Monthly Revenue) OVER (ORDER BY Month)

Technique Used:
1. Aggregate revenue for each month.
2. Store monthly revenue in a CTE.
3. Apply a running total using SUM() OVER().
4. Order by month number to maintain chronological order.

Business Use:
This analysis helps RetailIQ monitor cumulative
business growth throughout the year. It is useful
for revenue tracking, financial reporting, trend
analysis, forecasting, and executive dashboards.

Window Function Used:
SUM() OVER()

Reason:
Calculates a cumulative running total without
collapsing rows, making it ideal for trend analysis.

========================================================
*/

WITH monthly_revenue AS
(
    SELECT
        MONTH(o.order_date) AS month_number,
        MONTHNAME(o.order_date) AS month_name,

        SUM(oi.quantity * oi.unit_price) AS monthly_revenue

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        MONTH(o.order_date),
        MONTHNAME(o.order_date)
)

SELECT
    month_name,
    monthly_revenue,

    SUM(monthly_revenue) OVER
    (
        ORDER BY month_number
    ) AS running_revenue

FROM monthly_revenue

ORDER BY month_number;

/*
========================================================
MONTH-OVER-MONTH REVENUE GROWTH
(ADVANCED SQL - CTE + WINDOW FUNCTION)
========================================================

Purpose:
Calculate the month-over-month revenue growth by
comparing each month's revenue with the previous month.

Formula:
Monthly Revenue =
SUM(Quantity × Unit Price)

Growth % =
((Current Revenue - Previous Revenue)
 / Previous Revenue) × 100

Technique Used:
1. Aggregate monthly revenue in a CTE.
2. Use LAG() to retrieve the previous month's revenue.
3. Calculate the percentage growth between consecutive months.
4. Order by month number to maintain chronological order.

Business Use:
This analysis helps RetailIQ monitor business growth
over time, identify seasonal trends, evaluate sales
performance, and support forecasting and strategic
planning.

Window Function Used:
LAG()

Reason:
Retrieves the previous month's revenue without using
self-joins or subqueries, making month-over-month
comparisons simple and efficient.

========================================================
*/

WITH monthly_revenue AS
(
    SELECT
        MONTH(o.order_date) AS month_number,
        MONTHNAME(o.order_date) AS month_name,

        SUM(oi.quantity * oi.unit_price) AS total_revenue

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        MONTH(o.order_date),
        MONTHNAME(o.order_date)
)

SELECT
    month_name,
    total_revenue,

    LAG(total_revenue) OVER
    (
        ORDER BY month_number
    ) AS previous_month_revenue,

    ROUND
    (
        (
            total_revenue
            -
            LAG(total_revenue) OVER(ORDER BY month_number)
        )
        /
        LAG(total_revenue) OVER(ORDER BY month_number)
        *100,
        2
    ) AS growth_percentage

FROM monthly_revenue

ORDER BY month_number;
